### ISSUE TITLE
Test if we can use the latest Sphinx

### ISSUE THREAD

**Issue by zupo** [eestec/eestec.portal#22]
At https://github.com/eestec/eestec.portal/blob/master/buildout.d/versions.cfg#L14 we have a line that pins the version of Sphinx to 1.0.7 because at the time that file was made, the latest Sphinx release was broken.

We want to test if the bug that prevented us to use 1.0.8 is fixed in the latest release (1.1.3 as of this writing). How to test:
1. remove the line that pins Sphinx version
2. re-run buildout (`bin/buildout`)
3. re-run sphinx (`bin/sphinxbuilder`)
4. open `docs/html/index.html`with your browser and check that documentation is generated correctly
5. report your findings as a comment below

**Comment by Rotonen** [comment]
``` bash
bin/sphinxbuilder 
/Users/rotonen/koodaus/git/eestec.portal/bin/zopepy /Users/rotonen/koodaus/git/eestec.portal/bin/sphinx-build -b html -d /Users/rotonen/koodaus/git/eestec.portal/docs/doctrees   /Users/rotonen/koodaus/git/eestec.portal/docs /Users/rotonen/koodaus/git/eestec.portal/docs/html
Running Sphinx v1.1.3
loading pickled environment... done
building [html]: targets for 0 source files that are out of date
updating environment: 0 added, 1 changed, 0 removed
reading sources... [100%] index                                                                                                                                   
/Users/rotonen/koodaus/git/eestec.portal/docs/index.rst:7: WARNING: toctree contains reference to nonexisting document u'source'
../README.rst:9: WARNING: nonlocal image URI found: http://travis-ci.org/eestec/eestec.portal.png
looking for now-outdated files... none found
pickling environment... done
checking consistency... /Users/rotonen/koodaus/git/eestec.portal/docs/HISTORY.rst:: WARNING: document isn't included in any toctree
/Users/rotonen/koodaus/git/eestec.portal/docs/LICENSE.rst:: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [100%] index                                                                                                                                    
writing additional files... genindex search
copying downloadable files... [100%] /Users/rotonen/koodaus/git/eestec.portal/docs/specs/workflows/event_application_workflow.uxf                                 
copying static files... WARNING: html_static_path entry '/Users/rotonen/koodaus/git/eestec.portal/docs/_static' does not exist
done
dumping search index... done
dumping object inventory... done
build succeeded, 5 warnings.

Build finished. The HTML pages are in /Users/rotonen/koodaus/git/eestec.portal/docs/html.
```

**Comment by zupo** [comment]
Dude, don't take away entry-level tickets from people :). But yeah, seems that it works, please commit.

**Comment by andrejpan** [comment]
Unfortunately it did not pass at my computer...

╭─andrejpan:/home/andrejpan/koda/eestec/eestec.portal (master⚡) 
╰─$ bin/sphinxbuilder
/home/andrejpan/koda/eestec/eestec.portal/bin/zopepy /home/andrejpan/koda/eestec/eestec.portal/bin/sphinx-build -b html -d /home/andrejpan/koda/eestec/eestec.portal/docs/doctrees   /home/andrejpan/koda/eestec/eestec.portal/docs /home/andrejpan/koda/eestec/eestec.portal/docs/html
Running Sphinx v1.0.8
loading pickled environment... done
building [html]: targets for 15 source files that are out of date
updating environment: 0 added, 2 changed, 0 removed
reading sources... [ 50%] dev/local  
Exception occurred:
  File "/home/andrejpan/koda/eestec/eestec.portal/eggs/Sphinx-1.0.8-py2.7.egg/sphinx/util/nodes.py", line 114, in set_role_source_info
    inliner.reporter.locator(lineno)
AttributeError: Reporter instance has no attribute 'locator'
The full traceback has been saved in /tmp/sphinx-err-FYrzYi.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
Either send bugs to the mailing list at http://groups.google.com/group/sphinx-dev/,
or report them in the tracker at http://bitbucket.org/birkenfeld/sphinx/issues/. Thanks!

Build finished. The HTML pages are in /home/andrejpan/koda/eestec/eestec.portal/docs/html.

**Comment by domenkozar** [comment]
Let's just forget about this? It's really not relevant.
